import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Uptown Ultras</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <div className="flex flex-row h-screen justify-around my-8 w-11/12 mx-auto">
          <div className="flex justify-center w-2/3  bg-fixed bg-right-bottom bg-cover boa-bg">
            {" "}
            <div className="mx-auto flex flex-col justify-center">
              <h1 className="mt-6 p-2 rounded-lg bg-gray-200 bg-opacity-50 bg-origin-content mx-auto text-4xl text-black text-center font-bold font-rockSalt">
                Home of the Uptown Ultras
              </h1>
            </div>
          </div>
          <div className="w-1/4 border-2 rounded-lg"></div>
        </div>
      </div>
    </div>
  );
}
